dataContractSpecification: 0.9.3
id: urn:core.bronze.backofficebannersconfigurations_brz-latest
info:
  title: Configuración de Banners Publicitarios - Backoffice
  domain: core
  version: 1.0.0
  squad: SQ. CONNECT
  owner: Angello Sebastian Vasquez Carbajal
  contact:
    name: Enrique Huasupoma Malca
    email: enriquehuasupomam@yape.com.pe
    nickame: avloak
servers:
  prd:
    type: databricks
    server_environment: prd
    server_host: dbw-yadl3-eastus2-prd-001
    catalog: core
    schema: bronze
terms:
  usage: La información de esta tabla se utiliza para cruces con eventos de interacción
    y consultas del equipo de ML, contribuyendo al análisis de performance y a modelos
    de recomendación.
  limitations: Ninguna
tags:
- core
- bronze
- raw
- Backoffice
models:
  backofficebannersconfigurations_brz:
    description: 'Descripción de la tabla: Esta tabla almacena la configuración y
      atributos de los banners gestionados desde el backoffice, permitiendo su segmentación,
      personalización y control de visibilidad según tipo, producto, segmento de usuario
      y estado. Incluye información relevante para la gestión de banners funcionales
      y de donación, así como detalles de accesibilidad, fechas de vigencia, segmentación,
      y control de eliminación lógica.'
    type: table
    tableType: raw
    universeLogic: Carga directa
    fields:
      end_date:
        type: string
        description: 'Fecha de finalización de la vigencia del banner, configurada
          en el backoffice. El valor se encuentra en formato UTC-0. Formato: dd/MM/yyyy
          HH:mm:ssZ.'
        examples:
        - 09/03/2025 00:00:59+00
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: end_date
            xdataTypeField: string
      owner:
        type: string
        description: 'Owner provider configurado en el backoffice, utilizado para
          identificar a los usuarios a quienes se mostrará el banner según el owner
          provider. Este valor solo está presente cuando el banner es de tipo MASIVO.
          Valores posibles: BCP, NIUBIZ, YAPEDIGITAL, YAPEEMPRESA.'
        examples:
        - '{BCP, YAPEDIGITAL}'
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: owner
            xdataTypeField: string
      product:
        type: string
        description: Producto asociado al home banner, empleado para los clusters
          de NBP (Next Best Product) en el futuro.
        examples:
        - Recargas
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: product
            xdataTypeField: string
      __deleted:
        type: string
        description: Campo utilizado como convención de integración con Debezium.
          False indica que el registro no ha sido eliminado (registro activo), mientras
          que True indica que el registro ha sido eliminado (tombstone).
        examples:
        - 1
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: __deleted
            xdataTypeField: string
      deeplink:
        type: string
        description: Deeplink utilizado en el banner para redireccionar a los usuarios
          cuando interactúan con él.
        examples:
        - yape://yape.com.pe/app/recharges
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: deeplink
            xdataTypeField: string
      blacklist:
        type: string
        description: Corresponde a un arreglo de valores que indica la lista de segmentos
          que actuarán como blacklist dentro de la lógica del API Connect Hub. Si
          un segmento está incluido en esta lista, los usuarios pertenecientes a ese
          segmento no visualizarán el banner configurado.
        examples:
        - '{testqanewlabel40, testqanewlabel39}'
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: blacklist
            xdataTypeField: string
      description:
        type: string
        description: Descripción textual del banner creado, utilizada para funciones
          de accesibilidad en los dispositivos.
        examples:
        - Realiza compras con envios desde 10 soles por Yape Tienda
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: description
            xdataTypeField: string
      created_at:
        type: string
        description: 'Fecha de creación del home banner. El valor se encuentra en
          formato UTC-0. Formato: dd/MM/yyyy HH:mm:ssZ.'
        examples:
        - 09/03/2025 00:00:59+00
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: created_at
            xdataTypeField: string
      organization_name:
        type: string
        description: Nombre de la ONG u organización utilizado para crear el banner
          de tipo donación. Este campo solo tiene valor si el banner es de tipo donación.
        examples:
        - Perú Manos Unidas
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: organization_name
            xdataTypeField: string
      title:
        type: string
        description: Título asignado al banner dentro del backoffice.
        examples:
        - Envios a 10 soles
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: title
            xdataTypeField: string
      type:
        type: string
        description: 'Indica el tipo de banner. Puede ser funcional o de donación.
          Valores posibles: NAVIGATION, DONATION.'
        examples:
        - NAVIGATION
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: type
            xdataTypeField: string
      confirmation_name:
        type: string
        description: Nombre del mensaje de confirmación mostrado en el modal de donación.
          Este campo solo tiene valor si el banner es de tipo donación.
        examples:
        - Perú Manos Unidas
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: confirmation_name
            xdataTypeField: string
      banner_type_position:
        type: string
        description: Indica el tipo de configuración de segmentación del banner. Los
          valores determinan si es de tipo MASIVO (envíos según owner provider del
          usuario), SEGMENTADO (segmentación personalizada por bases), NBP (personalización
          a nivel de usuario) o DEFAULT (banners por defecto si un usuario no tiene
          banners pendientes).
        examples:
        - MASIVO
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: banner_type_position
            xdataTypeField: string
      petitioner:
        type: string
        description: Valor que indica el producto al que hace referencia la publicación,
          configurado en el backoffice desde una lista desplegable o campo de texto.
        examples:
        - RECARGAS
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: petitioner
            xdataTypeField: string
      url_image:
        type: string
        description: URL de la imagen utilizada para mostrar el banner en el carrusel
          de Yape.
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: url_image
            xdataTypeField: string
      updated_at:
        type: string
        description: 'Fecha de modificación de un registro del banner. El valor se
          encuentra en formato UTC-0. Formato: dd/MM/yyyy HH:mm:ssZ.'
        examples:
        - 09/03/2025 00:00:59+00
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: updated_at
            xdataTypeField: string
      segment:
        type: string
        description: Corresponde a un arreglo de valores que indica el listado de
          segmentos a los cuales se disponibilizará el banner. Este valor solo está
          presente cuando el banner es de tipo SEGMENTADO.
        examples:
        - '{testqanewlabel42, testqanewlabel43, testqanewlabel44}'
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: segment
            xdataTypeField: string
      id:
        type: string
        description: Identificador único del banner creado desde el backoffice, utilizado
          como clave primaria (PK).
        examples:
        - 5cbfce31eef3581dbb2e5a8490d4ac7b
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: id
            xdataTypeField: string
      phone_donation:
        type: string
        description: Número de celular de la ONG a la cual se realizarán los yapeos
          donativos. Este campo solo tiene valor si el banner es de tipo donación.
        examples:
        - 51999999999
        pii: true
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: phone_donation
            xdataTypeField: string
      position:
        type: string
        description: Posición relativa que tendrá el banner dentro del carrusel o
          listado de banners en los flujos que lo soporten.
        examples:
        - 1
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: position
            xdataTypeField: string
      view_scope:
        type: string
        description: Indica la pantalla en la que debe aparecer el banner configurado
          en el backoffice.
        examples:
        - BENEFICIOS_DMS
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: view_scope
            xdataTypeField: string
      start_date:
        type: string
        description: 'Fecha de inicio de la publicación del banner, configurada en
          el backoffice. El valor se encuentra en formato UTC-0. Formato: dd/MM/yyyy
          HH:mm:ssZ.'
        examples:
        - 09/03/2025 00:00:59+00
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: start_date
            xdataTypeField: string
      status:
        type: string
        description: 'Indica el estado del registro del banner. Valores posibles:
          BORRADOR (el registro aún se encuentra en borrador y puede ser modificado),
          VALIDACION (el registro se encuentra en validación por un owner), APROBADO
          (el registro está activado), ELIMINADO (el registro ha sido eliminado desde
          el backoffice).'
        examples:
        - APROBADO
        xqualityFieldValidations:
          xnullity: true
        lineage:
          inputFields:
          - namespace: Backoffice
            xsourceType: kafka
            name: db-yape3-eastus-connect-hub-qa.public.banner
            field: status
            xdataTypeField: string
      metadata:
        description: Metadata from kafka
        type: struct
        required: true
        fields:
          partition:
            description: Indica la división lógica y física de un tópico
            type: int
          offset:
            description: Indica la posición secuencial de un mensaje dentro de una
              partición
            type: bigint
          timestampType:
            description: Flag que indica el tipo de fecha; 0 fecha de creación del
              evento, 1 fecha en que se encola el evento
            type: string
          timestamp:
            description: Fecha en que se encola el evento cuando timestampType es
              1. Si timestampType es 0, corresponde a la fecha de creación del evento.
            type: timestamp
      document:
        description: JSON text from eventData
        type: string
        required: true
      auditTime:
        description: Fecha y hora de ejecucion de la rutina de carga al datalake en
          UTC-0.
        type: timestamp
        required: true
      p_auditDate:
        description: Fecha de ejecucion de la rutina de carga al datalake en UTC-0.
        type: date
        required: true
    config:
      clustering:
        description: Clustering for optimization
        fields:
        - auditTime
        - p_auditDate
      tableProperties:
        delta.logRetentionDuration: interval 30 days
        delta.deletedFileRetentionDuration: interval 30 days
        delta.autoOptimize.autoCompact: 'true'
        delta.autoOptimize.optimizeWrite: 'true'
servicelevels:
  frequency:
    description: La actualización de la data  sobre la configuración de banners se
      realizará todos los días a media noche + 1 min
    type: batch
    interval: daily
