name: Publish Artifacts

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar AzCopy
        run: |
          curl -sL https://aka.ms/downloadazcopy-v10-linux | tar -xz
          sudo mv ./azcopy_linux_amd64_*/azcopy /usr/bin/

      - name: Descargar archivos desde ADLS
        run: |
          azcopy copy "https://adlseu2yadlbackd02.blob.core.windows.net/develop?${{ secrets.SAS_TOKEN }}" "./" --recursive

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "feat: publish datacontract artifacts" || echo "No hay cambios"
          git push origin main

      - name: Crear Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "feat: publish datacontract artifacts"
          base: main
          branch: autogen-artifacts
          body: "Archivos publicados desde ADLS"
